.github/workflows/ci.yml
README.md

Closes https://github.com/nearform/optic-expo/issues/9
Adds a basic CI integration with one step for now.
- `yarn lint`

Chore | Setup basic Github Actions

---

.eslintrc
App.js
components/HomeHeaderRight.js
components/Main.js
components/screens/Home.js
components/screens/ScanNewSecretScreen.js
components/screens/TypeNewSecretScreen.js
context/authentication.js
context/secrets.js
lib/secretsManager.js
package.json
tests/Main.test.js
tests/secretsManager.test.js
yarn.lock

Closes #19
This PR introduces the following changes:
- Replace in-memory secret storage with the less ephemeral solution provided by the [AsyncStorage](https://docs.expo.io/versions/v40.0.0/sdk/async-storage/) RN library.
- Introduces a security layer around the storage solution using the [SecureStore](https://docs.expo.io/versions/latest/sdk/securestore/) package where available and a symmetrical encryption strategy with the cryptography tools provided by the [aes-js](https://www.npmjs.com/package/aes-js) library.
- Configure a new husky hook to run the project's unit tests before code is pushed upstream.

feat: use react-native storage

---

.gitignore
components/Secret.js
components/screens/Home.js
components/screens/TypeNewSecretScreen.js
context/authentication.js
context/secrets.js
lib/secretsService.js
package.json
tests/Main.test.js
tests/secretsManager.test.js
yarn.lock

Continuing from https://github.com/nearform/optic-expo/pull/42
Closes https://github.com/nearform/optic-expo/issues/5
- Updated home page UI
- Added features, generate/revoke token
- Added delete secret option
Will add/update some tests later.
https://user-images.githubusercontent.com/2510597/117008305-34ac9000-ad08-11eb-90d4-c162302a32db.mp4

feat: improve ui and continue from #42

---

src/lib/api.js
src/screens/Home.js
src/tests/Main.test.js

* Implementing push notification
* Implementing prompt to respond to notification
https://user-images.githubusercontent.com/27079992/135004687-a0658e57-1198-4164-a42d-2585c07f5782.mp4

feat: register mobile app for notifications

---

.github/dependabot.yml

* Ignoring all expo related packages since they need to be updated manually

chore(deps): ignoring all expo related udpates (83)

---

.husky/commit-msg
.husky/pre-commit
package.json
yarn.lock

chore: bumping husky from 4 to 7

---

babel.config.js
jest.setup.js
src/components/SecretCard/SecretCard.tsx
src/hooks/use-animated-transition.ts
src/screens/HomeScreen.test.tsx.snap.android
src/screens/HomeScreen.test.tsx.snap.ios

This PR adds a simple animation to the secret show hide action. 
The other mentioned animations in the issue (route transitions and fab button animations) seem to be already  implemented as can be seen in the screen recording.
https://user-images.githubusercontent.com/537189/141766144-d741ab8a-dad6-410a-9677-a7314ec75aff.mov
- Due to the way the animation works, the secret view is not removed from the component hierarchy and is instead hidden and set to height 0. For this reason, the homescreen snapshots were updated.

feat: add micro interactions

---

README.md

Update link to new figma file.

docs: update link to figma design file

---

.github/workflows/ci.yml

Disables expo preview for dependabot PRs.

chore: disable expo preview for dependabot

---

README.md
src/components/SecretCard/SecretCard.tsx
src/screens/HomeScreen.tsx

Add loading indicators & update docs

---

package.json
src/screens/HomeScreen.test.tsx.snap.android
src/screens/HomeScreen.test.tsx.snap.ios
yarn.lock

chore(deps): bump react-native-countdown-circle-timer to 3.0.8

---

src/components/HomeHeaderRight.tsx

feat: add numeric badge for pending notifications

---

.eslintrc.js
package.json
src/context/PendingNotificationsContext.tsx
src/context/SecretsContext.tsx
src/screens/TokenScreen.tsx
yarn.lock

closes #553
Added `react/no-unstable-nested-components` exception for allowAsProps as the current usage seems valid based on the api provided by `react-native-paper`.

Linting fixes

---

.github/workflows/ci.yml

chore: remove disable mocked warning env var in CI

---

.github/workflows/expo-eas-build.yml

fix: gh action

---

.github/workflows/cd.yml
.github/workflows/release.yml
README.md
app.config.js

fix: readme and buildNumber in ios config

---

package.json
src/components/Scanner.tsx
yarn.lock

fix: scan qr

---

.github/workflows/ci.yml

Don't run eas update on dependabot prs

---

src/components/NotificationCard.tsx
src/context/PendingNotificationsContext.tsx
src/types.ts

fix: notifications in ios were all marked as expired

---

.github/workflows/release.yml

fix: gh release action. use yarn to install

---

.github/workflows/release.yml
eas.json

add submit profiles to eas.json

---

.github/workflows/expo-eas-clean.yml

add checkout to clean action

---

.github/workflows/expo-eas-clean.yml
.github/workflows/expo-eas-update.yml

"Fix path for expo token"

---

src/components/Login.tsx
src/context/AuthContext.tsx
src/screens/AuthScreen.tsx

feat: add a hidden password login just for google play review

---

.github/workflows/ci.yml
.github/workflows/expo-eas-clean.yml

prevent eas-clean on dependabot

---

README.md

chore: add store links

---

src/screens/ExportFileSecret.tsx
src/screens/ImportFileSecret.tsx

fix: issue 760

---

package.json
src/Main.test.tsx
src/Main.tsx
src/context/SecretsContext.tsx
src/screens/AuthScreen.test.tsx
src/screens/HomeScreen.tsx
src/screens/TypeScreen.test.tsx
yarn.lock

775 use expo splash screen instead of expo app loading

---

.github/workflows/expo-eas-update.yml

chore: replace deprecated set-output command

---

.github/workflows/ci.yml

fix: check dependencies by expo is not working properly
