- README.md
The CI badge on the `README` was pointing to the wrong URL.
> chore | update README.md badge

- .eslintrc
- components/Actions.js
- components/Auth.js
- components/EmptyTokensText.js
- components/Home.js
- components/TypeNewSecret.js
- components/typography.js
A little housekeeping work here based on few comments and slack discussions around #13.
Effectively this PR do:
- Add the "no-use-before-define" eslint rule to our configuration to aid on enforcing the consensus arrived regarding the order in which ui strings and styles constants are defined in component files.
- Update event handler function name in `<TypeNewSecret />` function to a more meaningful one.
> chore: enforce identifier definition order

- components/Actions.js
- components/EmptyTokensText.js
- components/Home.js
- components/IconButtonWithLabel.js
- components/typography.js
- lib/defaultTheme.js
- package.json
- tests/Main.test.js
- yarn.lock
As I was working on the scan a QR code feature, I updated the Blank tokens UI to match the design. I thought it would make sense to separate these two changes out and land them separately.
- Added a couple of new typography styles. `Headline5` and `Caption` typography style (from figma)
- I've updated the `Headline` component to accept a `level` prop. (Let me know if you feel strongly against this)
> feat: update blank tokens screen to match design

- src/screens/TokensListScreen.test.tsx
- src/screens/TokensListScreen.test.tsx.snap.android
- src/screens/TokensListScreen.test.tsx.snap.ios
- src/screens/TokensListScreen.tsx
See comment from PR #222:
>  If the filter result is zero, could we filter by token?
>  For example: I see a token on my CI, and I want to check that the description match because I don't remember if I have copied&pasted it from another setup
This PR also disables the auto correct on the search input
Closes #262
> feat: Allow user to filter by token

- src/lib/secure-storage/index.test.tsx
- src/lib/secure-storage/storage.test.tsx
- src/lib/secure-storage/storage.ts
Added few unit tests to cover most of the exceptions in secure-storage.
Fixed a minor bug.
Closes #36
> Added unit tests to cover exception handling in secure-storage

- src/Main.tsx
- src/components/HomeHeaderRight.tsx
- src/context/AuthContext.tsx
- src/screens/SettingsScreen.test.tsx
- src/screens/SettingsScreen.test.tsx.snap.android
- src/screens/SettingsScreen.test.tsx.snap.ios
- src/screens/SettingsScreen.tsx
- src/types.ts
Add email and logout button in the settings screen
Linked issue #322
> Display email address

- README.md
adding a simple user guide to easy the newcomers to use this app
> chore: add user guide

- package.json
- src/App.tsx
- src/Main.tsx
- src/components/HomeHeaderRight.tsx
- src/components/NotificationCard.tsx
- src/context/PendingNotificationsContext.tsx
- src/screens/HomeScreen.test.tsx
- src/screens/HomeScreen.tsx
- src/screens/NotificationsScreen.tsx
- src/screens/OtpRequestScreen.tsx
- src/types.ts
- yarn.lock
- Adds a new "notifications" section, where all pending notifications are listed to be handled (rejected, accepted, or dismissed in case they already expired).
- The pending notifications are persisted.
- The push notifications are automatically dismissed if the OTP requests are handled directly via the notifications section instead of doing that through the notifications provided by the smartphone's interface.
- For now, we don't keep track of all previous accepted & rejected OTP requests (once we handle them, we discard this information). I believe this should be discussed with more people, as it's a more advanced feature resembling a sort of audit log, and we might want to have support from the API side.
- Right now, the "notifications bell" does not have a nice numerical counter, it …
> feat: track pending notifications

- package.json
- src/Main.test.tsx
- src/lib/secretsManager.test.tsx
- src/lib/secure-storage/aes.ts
- src/lib/secure-storage/index.test.tsx
- src/lib/secure-storage/storage.test.tsx
- src/lib/secure-storage/storage.ts
- src/screens/CreateTokenScreen.test.tsx
- src/screens/HomeScreen.test.tsx
- src/screens/TokenScreen.test.tsx
- src/screens/TypeScreen.test.tsx
- yarn.lock
Resolves the issues with upgrading to ts-jest@28.0.7  that you see in the action logs for https://github.com/nearform/optic-expo/pull/599
Main resolution is is removal of ts-jest/utils mocked as this is now built into jest (see https://github.com/kulshekhar/ts-jest/issues/3327)
> fix: update unit tests to remove usage of mocked from ts-jest/utils

- src/screens/CreateTokenScreen.test.tsx
- src/screens/TokenScreen.test.tsx
Updated tests for token screen components to not produce error logs. #612
> Fix: Warning texts in tests.

- .eslintignore
- package.json
- patch/Linking.js
- src/context/AuthContext.tsx
> fix: opening updates in expo go in android

- README.md
> fix: add sections for basic setup and providing apple developer access

- src/components/Actions.tsx
- src/screens/HomeScreen.test.tsx.snap.android
- src/screens/HomeScreen.test.tsx.snap.ios
I removed the `portal` wrapping the `FAB.Group` component so it's rendered at the page where it's being used but according to the react-native-paper docs it could cause z-index issues. I did try a couple of different scenarios (long list of secrets scrolling under the button, trying to use the buttons and dropdowns while close to the FAB) and it all seemed to work fine.
If that's not an acceptable solution I can try to investigate deeper since the logic to show/hide it seems correct (it uses react-navigation's isFocused hook to check whether a page is focused and shows the button only if the homepage is focused).
Closes #831.
> fix: show `add secret` button only on home screen

- .github/workflows/release.yml
We're updating this action in a couple of repositories to test it before fully releasing it.
After the test period this should be changed back to the latest version of optic-release-automation-action.
References nearform/optic-release-automation-action#186
> Use pre-release version of optic-release-automation-action

- .github/workflows/release.yml
Reverts `optic-release-automation-action` to version 4 in the release workflow. Previously, it was testing the WIP on monorepos.
> chore: revert optic-release-automation version to v4

- package.json
- src/screens/ExportFileSecret.test.tsx.snap.android
- src/screens/ExportFileSecret.test.tsx.snap.ios
- src/screens/HomeScreen.test.tsx.snap.android
- src/screens/HomeScreen.test.tsx.snap.ios
- src/screens/ImportFileSecret.test.tsx.snap.android
- src/screens/ImportFileSecret.test.tsx.snap.ios
- src/screens/SettingsScreen.test.tsx.snap.android
- src/screens/SettingsScreen.test.tsx.snap.ios
- src/screens/TypeScreen.test.tsx.snap.android
- src/screens/TypeScreen.test.tsx.snap.ios
- yarn.lock
replacing this other PR: https://github.com/nearform/optic-expo/pull/909
> chore(deps): bump react-native-paper to 5.1.2

- .github/workflows/expo-eas-update.yml
to fix: https://github.com/nearform/optic-expo/actions/runs/3882491248/jobs/6622762211
> chore: gh action steps for preview links run only for pull requests

- .github/workflows/ci.yml
Added the permissions to update the PR (in order to close it) and cancel the action.
Closes #1137
> fix: add correct permissions to ci workflow

- eas.json
This is to ensure that android deployments are released to immediately to users without having to go through the manual process of creating a production release on the play store.
fixes #1245
> added production track to android

- src/App.tsx
- src/context/InitalLoadingContext.tsx
- src/screens/HomeScreen.test.tsx
- src/screens/HomeScreen.tsx
Adds a conditional to the notification listener useEffect to use the necessary callbacks when a OTP request is pressed whilst the app is closed.
closes: https://github.com/nearform/optic-expo/issues/1155
> fix: allows OTP to be approved from a cold start

- .github/workflows/expo-eas-update.yml
- package.json
- yarn.lock
Closes item 1 in the post-migration steps
Relates to #1388
> Post SDK 52 migration | Step 1: update eas-update ci command

- .github/workflows/cd.yml
Closes item 2 in the post-migration steps
Relates to #1388
> Post SDK 52 migration | Step 2: disable app stores cd release step
